<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="283" started-at="2016-07-28T01:57:51Z" finished-at="2016-07-28T01:57:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="283" started-at="2016-07-28T01:57:51Z" finished-at="2016-07-28T01:57:51Z">
      <class name="com.test.ColSecondTest">
        <test-method status="PASS" signature="checkWordInsert()[pri:0, instance:com.test.ColSecondTest@5574ee1a]" name="checkWordInsert" duration-ms="15" started-at="2016-07-27T18:57:51Z" finished-at="2016-07-27T18:57:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkWordInsert -->
        <test-method status="FAIL" signature="checkWordUpdate()[pri:0, instance:com.test.ColSecondTest@5574ee1a]" name="checkWordUpdate" duration-ms="2" started-at="2016-07-27T18:57:51Z" finished-at="2016-07-27T18:57:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Adding> but was:<updating>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Adding> but was:<updating>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at com.test.ColSecondTest.checkWordUpdate(ColSecondTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkWordUpdate -->
      </class> <!-- com.test.ColSecondTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
